-- comandos sql se dividem em duas linguagens
-- ------------------------------------------------------------------
-- ddl (data definition language)
-- => comandos de definição do banco de dados
-- exemplos: CREATE DATABASE NAME
-- 			  DROP DATABASE 
-- 			 CREATE TABLE NAME (COLUNAS)
-- 			 DROP TABLE NAME
-- ---------------------------------------------
-- DML (Data Manipulation Language)
-- => Comandos de manipulação de dados
-- Ex: SELECT COLUNAS FROM TABELA
-- 	   INSERT INTO TABELA (COLUNAS) VALUES (VALORES)
--     DELETE FROM TABELA
--     UPDATE COLUNAS FROM TABELA
